### ISSUE TITLE
29 Febbraio uwu

### ISSUE THREAD

**Issue by Nikicoraz** [FedericoSlongo/Date_Checker#1]
Il ventinove febbraio (Il mio giorno preferito!1!!!!11!!!) no è supportato.
Io mnolto triste
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA UwU
# 29 Febbraio

**Comment by FedericoSlongo** [comment]
UwU

**Comment by Nikicoraz** [comment]
F

**Comment by Nikicoraz** [comment]
A

**Comment by FedericoSlongo** [comment]
OwO
